<?php
// ../reports/employee-list.php
include_once('../include/connection.php');

// Check if user is logged in
session_start();
if (!isset($_SESSION['userid']) || empty($_SESSION['userid'])) {
    header("Location: ../index.php");
    exit();
}

// Get all active employees for printing
$sql = "SELECT employee_id, first_name, last_name, phone, email, position, hire_date, status 
        FROM employees 
        WHERE status = 'active'
        ORDER BY last_name ASC, first_name ASC";
$result = mysqli_query($con, $sql);

// Get company info
$company_name = "RWELL";
$report_title = "Active Employees List";
$report_date = date('F j, Y');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $company_name; ?> - Employee List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #464660;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #464660;
            font-size: 28px;
        }
        .header h3 {
            margin: 10px 0 0;
            color: #666;
            font-weight: normal;
        }
        .company-info {
            margin-bottom: 20px;
            text-align: center;
        }
        .report-info {
            margin-bottom: 20px;
            font-size: 14px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background: #464660;
            color: white;
            padding: 12px;
            text-align: left;
            font-size: 14px;
        }
        td {
            padding: 10px 12px;
            border-bottom: 1px solid #ddd;
            font-size: 13px;
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        .status-active {
            color: #28a745;
            font-weight: bold;
        }
        .print-date {
            text-align: right;
            margin-bottom: 20px;
            font-size: 12px;
            color: #666;
        }
        @media print {
            body {
                margin: 20px;
            }
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #464660; color: white; border: none; border-radius: 4px; cursor: pointer;">
            <i class="fas fa-print"></i> Print / Save PDF
        </button>
        <button onclick="window.close()" style="padding: 10px 20px; background: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer; margin-left: 10px;">
            <i class="fas fa-times"></i> Close
        </button>
    </div>

    <div class="header">
        <h1><?php echo $company_name; ?></h1>
        <h3><?php echo $report_title; ?></h3>
    </div>

    <div class="report-info">
        <div>Date Generated: <?php echo $report_date; ?></div>
        <div>Total Active Employees: <?php echo mysqli_num_rows($result); ?></div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Employee Name</th>
                <th>Position</th>
                <th>Contact Number</th>
                <th>Email Address</th>
                <th>Hire Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $counter = 1;
            while ($row = mysqli_fetch_assoc($result)): 
            ?>
            <tr>
                <td><?php echo $counter++; ?></td>
                <td><?php echo htmlspecialchars($row['last_name'] . ', ' . $row['first_name']); ?></td>
                <td><?php echo htmlspecialchars($row['position']); ?></td>
                <td><?php echo htmlspecialchars($row['phone']); ?></td>
                <td><?php echo htmlspecialchars($row['email']); ?></td>
                <td><?php echo date('M d, Y', strtotime($row['hire_date'])); ?></td>
                <td class="status-active">Active</td>
            </tr>
            <?php endwhile; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>This is a system-generated report. For official use only.</p>
        <p>Generated by: <?php echo $_SESSION['username']; ?> | <?php echo date('h:i A'); ?></p>
    </div>

    <script>
        // Auto-trigger print dialog (optional)
        // window.onload = function() { window.print(); }
    </script>
</body>
</html>